version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v1.5.8

    branches:
      only: master

    steps:
      - checkout
      - run: cp android/local.properties.ci android/local.properties

      - run: ssh-keyscan vps.florentpastor.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "25:1a:cb:cd:e7:e9:12:61:3b:2b:b0:9e:c2:0c:2e:c3"
      - run:
          name: import secret files
          command: |
            scp ubuntu@vps.florentpastor.com:/home/ubuntu/circleci/android/key.properties android/
            scp ubuntu@vps.florentpastor.com:/home/ubuntu/circleci/android/key.jks /home/cirrus/

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build appbundle

      - store_artifacts:
          path: build/app/outputs/bundle/release/app-release.aab