version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v1.5.8

    branches:
      only: master

    steps:
      - checkout
      - run: cp android/local.properties.ci android/local.properties

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build appbundle

      - store_artifacts:
          path: build/app/outputs/bundle/release/app-release.aab